version: '3.7'

services:
  database:
    container_name: database
    image: postgres:14.2-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file:
      - ./.env
    restart: always

  backend:
    container_name: backend
    build: ./backend
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             python manage.py loaddata data &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static-volume:/home/app/backend/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - database
    restart: always

  server:
    container_name: nginx
    build: ./nginx
    volumes:
      - static-volume:/home/app/backend/staticfiles
    ports:
      - '80:80'
    restart: always

volumes:
  postgres-data:
  static-volume:
